### ISSUE TITLE
Moving away from a single markdown file?

### ISSUE THREAD

**Issue by kud1ing** [kud1ing/awesome-rust#190]
Since the Markdown file has grown a bit, i am considering extracting the data to a file (maybe JSON) and generating HTML from it.

Disadvantages:
- there is an additonal generator step
- contributors might expect a Markdown file

Advantages:
- the data file could be reused easier by other projects
- entries can show up in multiple sections without duplicating data
- less boilerplate code for contributors, less possibilities for errors
- the data can be checked and enriched easier. E.g. a script could check whether the links in the data file are correct or whether projects have (now) working Travis/Cargo URLs
- no manual sorting necessary anymore
- consistent output format across all entries
- the output format can be adjusted easier in the generator

**Comment by suhr** [comment]
See https://rust.libhunt.com/

**Comment by kud1ing** [comment]
@suhr Yes, but i don't know where the data is hosted so that is available to the community.

**Comment by jeffparsons** [comment]
I heartily support this move. One application I'd be keen on would be tagging of projects paired with (client-side) search.

**Comment by Anachron** [comment]
I hate JSON with a passion. Maybe it is because it cannot have comments? 

I suggest using something like TOML instead.

**Comment by cetra3** [comment]
How about you use my tool to combine them:

https://github.com/cetra3/mdcollate

**Comment by kud1ing** [comment]
@Anachron I am not a huge fan of JSON either, but my aversion for external code dependencies is greater. ;(

**Comment by hauleth** [comment]
For human readable format I would prefer YAML over JSON as is more flexible and easier to parse by wetware.

**Comment by Limeth** [comment]
There are human-readable derivates of JSON. One of them is called HOCON, IIRC.

**Comment by hauleth** [comment]
But why not use human-readable JSON superset - YAML?
--

Łukasz Niemier
lukasz@niemier.pl

**Comment by suhr** [comment]
@Anachron Do you hate [JSON5](http://json5.org/) too?

PS: still, better to use TOML since it's much more popular.

**Comment by Qard** [comment]
I think this bikeshed should be painted blue. :trollface: 

Seriously though, the storage format is irrelevant. The issue is not about which storage format is superior, it's about whether the content of this repo should be accessible as data and used to generate human-consumable pages.

Personally, I don't feel like there's a lot of value to content as data for this repo. Seems to me like the effort of building a generator and converting the existing content would far outweigh the small advantage of avoiding data duplication and sorting.

As a side note, there are already tools for validating links in markdown files, so you could just use those.

Personally, I'd rather just see the single markdown file split into multiple markdown files.

**Comment by pravic** [comment]
http://awesome-python.com for example. It is a single file too, but with TOC on left side.

**Comment by nasa42** [comment]
Would the format of http://libs.rs/ be an acceptable replacement? This is basically just bunch of TOML files - https://github.com/nasa42/libs.rs/tree/master/categories (and some scripts to generate HTML files periodically).

@kud1ing happy to give you access to the libs.rs repository.
