### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [kud1ing/awesome-rust#21]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by kud1ing** [comment]
That's an interesting idea.

I think this is not a good fit for "awesome-rust" at this time, because Rust is a very young language. Quite some projects are started, but not always finished. This project started as a spin-off from a similar page in the Rust wiki. The main goal here is to have less entries and more quality of entries. I am not convinced that more contributors will support this goal.
